docs: update gRPC related docs
GreptimeTeam/docs pull request #265
Opened 2023-03-22 10:50 UTC by MichaelScofield

close #264

2023-03-24 09:29 UTC, xtang approved these changes
LGTM

2023-03-24 09:31 UTC, xtang commented on docs/user-guide/supported-protocols/grpc.md
> +- [Java](../java-sdk)
```suggestion
- [Java](../java-sdk/java-sdk)
```

2023-03-24 09:32 UTC, xtang requested changes
fixed the java_sdk path

2023-03-27 07:17 UTC, MichaelScofield commented
@xtang PTAL

2023-03-28 02:38 UTC, xtang approved these changes
LGTM

2023-03-28 02:38 UTC, xtang commented
@killme2008 PTAL

2023-03-28 02:41 UTC, killme2008 approved these changes
LGTM

2023-03-28 02:42 UTC, merged