style: update image style
GreptimeTeam/docs pull request #575
Opened 2023-09-22 03:26 UTC by nicecui

2023-09-22 03:29 UTC, sunng87 commented
we can out example svg out of the public directory, which will be deployed.

2023-09-22 03:33 UTC, zhaoyingnan01 approved these changes

2023-09-22 03:48 UTC, sunng87 commented
also use monospaced font for code, even in the image

2023-09-22 08:30 UTC, sunng87 approved these changes

2023-09-22 08:40 UTC, sunng87 requested changes
![Uploading image.png…]()
typo

2023-09-22 08:50 UTC, sunng87 approved these changes

2023-09-25 02:46 UTC, xtang approved these changes

2023-09-25 02:47 UTC, merged