docs: script setup more details
GreptimeTeam/docs pull request #706
Opened 2023-12-08 09:37 UTC by discord9

## What's Changed in this PR
Add more explain in setting up Python for scripting

## Checklist

- [x] Please ensure that the content in `summary.yml` matches the current document structure when you changed the document structure.
- [x] This change requires follow-up update in localized docs.

2023-12-14 02:47 UTC, nicecui commented on docs/v0.4/en/user-guide/scripts-&-functions/getting-started.md
> +If you are using greptime's docker image, then it is already set up for scripting functionality, so you can skip this step.
```suggestion
If you are using Greptime's docker image, then it is already set up for scripting functionality, so you can skip this step.
```

2023-12-14 02:47 UTC, nicecui commented on docs/v0.4/zh/user-guide/scripts-&-functions/getting-started.md
> +如果您正在使用greptime的Docker镜像，那么它已经设置好了脚本功能，您可以跳过这一步。
```suggestion
如果您正在使用 Greptime 的 Docker 镜像，那么它已经设置好了脚本功能，您可以跳过这一步。
```

2023-12-14 02:47 UTC, nicecui commented on docs/v0.4/zh/user-guide/scripts-&-functions/getting-started.md
> +如果您希望使用带有pyo3功能的greptime二进制文件，首先需要知道您的greptime二进制文件所需的Python版本。您可以通过运行`ldd greptime | grep 'libpython'`（或在Mac上运行`otool -L greptime|grep Python.framework`）来检查。然后安装相应的Python版本（例如，`libpython3.10.so`需要Py
```suggestion
如果您希望使用带有 pyo3 功能的 Greptime 二进制文件，首先需要知道您的 Greptime 二进制文件所需的 Python 版本。您可以通过运行 `ldd greptime | grep 'libpython'`（或在 Mac 上运行 `otool -L greptime|grep Python.framework`）来检查。然后安装相应的 Python 版本（例如，`libpython3.10.so` 需要 Python 3.10 ）。
```

2023-12-14 02:47 UTC, nicecui commented on docs/v0.4/zh/user-guide/scripts-&-functions/getting-started.md
> +使用conda创建一个Python 3环境。Conda是管理Python环境的强大工具，请参阅[官方文档](https://docs.conda.io/en/latest/miniconda.html)以获取更多信息。
```suggestion
使用 Conda 创建一个Python 3环境。Conda 是管理 Python 环境的强大工具，请参阅[官方文档](https://docs.conda.io/en/latest/miniconda.html)以获取更多信息。
```

2023-12-14 02:47 UTC, nicecui commented on docs/v0.4/zh/user-guide/scripts-&-functions/getting-started.md
> +您可能需要为您的Python共享库设置正确的`LD_LIBRARY_PATH`，例如，对于conda环境，您需要将`LD_LIBRARY_PATH`（或`DYLD_LIBRARY_PATH`）设置为`$CONDA_PREFIX/lib`。您可以通过运行`ls $CONDA_PREFIX/lib | grep 'libpython'`来检查该路径是否包含正确的Python共享库，并确认版本是否正确
```suggestion
您可能需要为您的 Python 共享库设置正确的 `LD_LIBRARY_PATH`，例如，对于 Conda 环境，您需要将 `LD_LIBRARY_PATH`（或`DYLD_LIBRARY_PATH`）设置为 `$CONDA_PREFIX/lib`。您可以通过运行`ls $CONDA_PREFIX/lib | grep 'libpython'` 来检查该路径是否包含正确的 Python 共享库，并确认版本是否正确。
```

2023-12-14 02:47 UTC, nicecui commented on docs/v0.4/en/user-guide/scripts-&-functions/getting-started.md
> +If you want to use the greptime binary with the pyo3 feature, you first need to determine which version of Python is required for your greptime binary. You can check this by running `ldd greptime | g
```suggestion
If you want to use the Greptime binary with the pyo3 feature, you first need to determine which version of Python is required for your Greptime binary. You can check this by running `ldd greptime | grep 'libpython'` (or `otool -L greptime|grep Python.framework` on Mac), and then install the corresponding Python version (e.g., `libpython3.10.so` requires Python 3.10).
```

2023-12-14 11:40 UTC, nicecui commented on docs/v0.4/zh/user-guide/scripts-&-functions/getting-started.md
> +使用 Conda 创建一个Python 3环境。Conda 是管理 Python 环境的强大工具，请参阅[官方文档](https://docs.conda.io/en/latest/miniconda.html)以获取更多信息。
```suggestion
使用 Conda 创建一个 Python3 环境。Conda 是管理 Python 环境的强大工具，请参阅[官方文档](https://docs.conda.io/en/latest/miniconda.html)以获取更多信息。
```

2023-12-14 11:40 UTC, nicecui approved these changes

2023-12-15 09:18 UTC, xtang requested changes

2023-12-15 09:18 UTC, xtang commented on docs/v0.4/en/user-guide/scripts-&-functions/getting-started.md
> +If you are using Greptime's docker image, then it is already set up for scripting functionality, so you can skip this step.
```suggestion
If you are using Greptime's docker image, no need to set up scripting again—it's ready to go.
```

2023-12-15 09:18 UTC, xtang commented on docs/v0.4/en/user-guide/scripts-&-functions/getting-started.md
> +If you want to use the Greptime binary with the pyo3 feature, you first need to determine which version of Python is required for your Greptime binary. You can check this by running `ldd greptime | g
```suggestion
If you want to use the Greptime binary with the pyo3 feature, first figure out which Python version you need. Check by running `ldd greptime | grep 'libpython'` (or `otool -L greptime|grep Python.framework` on Mac), then install the corresponding Python version (e.g., `libpython3.10.so` requires Python 3.10).
```

2023-12-15 09:18 UTC, xtang commented on docs/v0.4/en/user-guide/scripts-&-functions/getting-started.md
> +To create a Python 3 environment using conda, which is a useful tool for managing Python environments, please refer to the [official documentation](https://docs.conda.io/en/latest/miniconda.html) for
```suggestion
To set up a Python 3 environment using conda, a handy tool for managing Python environments, please refer to the [official documentation](https://docs.conda.io/en/latest/miniconda.html) for more information.
```

2023-12-15 09:18 UTC, xtang commented on docs/v0.4/en/user-guide/scripts-&-functions/getting-started.md
> +You may need to set the correct `LD_LIBRARY_PATH` for your Python shared library. For example, for the conda environment, you need to set `LD_LIBRARY_PATH` (or `DYLD_LIBRARY_PATH`) to `$CONDA_PREFIX/
```suggestion
You may have to adjust the correct `LD_LIBRARY_PATH` for your Python shared library. For example, in the conda environment, set `LD_LIBRARY_PATH` (or `DYLD_LIBRARY_PATH`) to `$CONDA_PREFIX/lib`. To ensure the correct Python shared library is in this path, run `ls $CONDA_PREFIX/lib | grep 'libpython'` and verifty that the version is correct.
```

2023-12-20 03:55 UTC, xtang commented on docs/v0.4/en/user-guide/scripts-&-functions/getting-started.md
> +If you are using Greptime's docker image, no need to set up scripting again—it's ready to go.
```suggestion
If you are using Greptime's docker image, no need to set up scripting again—it's ready to use.
```

2023-12-20 03:56 UTC, xtang approved these changes

2023-12-20 03:56 UTC, merged